### ISSUE TITLE
doesnt build on windows

### ISSUE THREAD

**Issue by dsisnero** [yoshoku/numo-blis#1]
C:\WINDOWS\system32>gem install numo-blis
Fetching numo-linalg-0.1.7.gem
Fetching numo-blis-0.2.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed numo-linalg-0.1.7
Building native extensions. This could take a while...
ERROR:  Error installing numo-blis:
        ERROR: Failed to build gem native extension.

    current directory: F:/windows/tools/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/gems/numo-blis-0.2.0/ext/numo/blis
F:/windows/tools/ruby/Ruby30-x64/bin/ruby.exe -I F:/windows/tools/ruby/Ruby30-x64/lib/ruby/site_ruby/3.0.0 -r ./siteconf20210913-28152-uug2t1.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=F:/windows/tools/ruby/Ruby30-x64/bin/$(RUBY_BASE_NAME)
        --enable-threading
F:/windows/tools/ruby/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `spawn': Exec format error - ./configure --enable-cblas --enable-threading=openmp --prefix=F:/windows/tools/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/gems/numo-blis-0.2.0/vendor CC='x86_64-w64-mingw32-gcc' CXX='x86_64-w64-mingw32-gcc -E' auto (Errno::ENOEXEC)
        from F:/windows/tools/ruby/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from F:/windows/tools/ruby/Ruby30-x64/lib/ruby/3.0.0/open3.rb:102:in `popen3'
        from F:/windows/tools/ruby/Ruby30-x64/lib/ruby/3.0.0/open3.rb:289:in `capture3'
        from extconf.rb:75:in `block in <main>'
        from extconf.rb:73:in `chdir'
        from extconf.rb:73:in `<main>'
Downloading BLIS 0.8.1.
Unpacking BLIS tgz file.
Configuring BLIS.

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  F:/windows/tools/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/numo-blis-0.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in F:/windows/tools/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/gems/numo-blis-0.2.0 for inspection.
Results logged to F:/windows/tools/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/numo-blis-0.2.0/gem_make.out

**Comment by dsisnero** [comment]
still fails to build on windows

https://gist.github.com/dsisnero/5e03021f49f6c57c2c2a03ea075f04e7
